CREATE TABLE Measurments(
Id INTEGER NOT NULL CONSTRAINT PK_Measurments PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE ON UPDATE CASCADE,
chest TEXT(50),
bicep TEXT(50),
gluteus TEXT(50),
calf TEXT(50),
waistline TEXT(50)
)