CREATE TABLE Plans_Rows(
Id INTEGER NOT NULL CONSTRAINT PK_Plans_Rows PRIMARY KEY AUTOINCREMENT,
plan_id INTEGER NOT NULL REFERENCES Plans(Id) ON DELETE CASCADE ON UPDATE CASCADE,
exercise_id INTEGER NOT NULL REFERENCES Exercises(Id) ON DELETE CASCADE ON UPDATE CASCADE,
reps_id INTEGER NOT NULL REFERENCES Reps(Id) ON DELETE CASCADE ON UPDATE CASCADE,
week_number INTEGER NOT NULL,
weight TEXT(10),
rest TEXT(20),
band TEXT(30),
executed_reps TEXT(50)
)

