-- SQLite
CREATE TABLE Plans(
Id INTEGER NOT NULL CONSTRAINT PK_Plans PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL REFERENCES Users(Id) ON DELETE CASCADE ON UPDATE CASCADE,
creation_date DATETIME,
start_date START_DATE,
end_date END_DATE
)

DROP table Plans