drop table AspNetRoleClaims
drop table AspNetRoles
drop table AspNetUserClaims
drop table AspNetUserLogins
drop table AspNetUserRoles
drop table AspNetUserTokens
drop table AspNetUsers
drop table Exercises
drop table Measurments
drop table Plans
drop table Plans_Rows
drop table Reps
drop TABLE __EFMigrationsHistory